spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: cavidabdullayevv20@gmail.com
    password: iysn qafe pcxh gqsh
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true